version: '2'

services:
  cassandra1:
     image: com.palantir.docker/atlas-cassandra:2.2-v0.1
     environment:
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_ENDPOINT_SNITCH=PropertyFileSnitch
      - LOCAL_JMX=no

  cassandra2:
    image: com.palantir.docker/atlas-cassandra:2.2-v0.1
    environment:
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_ENDPOINT_SNITCH=PropertyFileSnitch
      - LOCAL_JMX=no

  cassandra3:
    image: com.palantir.docker/atlas-cassandra:2.2-v0.1
    environment:
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_ENDPOINT_SNITCH=PropertyFileSnitch
      - LOCAL_JMX=no

  ete1:
    build: .
    command: bash -c 'cp var/conf/atlasdb-ete.no-leader.multiple-cassandra.client.yml var/conf/atlasdb-ete.yml && dockerize -timeout 240s -wait tcp://cassandra1:9160 -wait tcp://cassandra2:9160 -wait tcp://cassandra3:9160 && service/bin/init.sh console'
    environment:
      - ME=ete1
    ports:
      - "3828"
