version: '2'

services:
    cassandra:
        image: com.palantir.docker/atlas-cassandra:2.2-v0.1
        ports:
        - "9160"
        - "9042"
        - "7199"
        environment:
        - LOCAL_JMX=no
    ete:
        image: java:openjdk-8u72-jre
        links:
        - cassandra
        volumes:
        - ~/.gradle:/root/.gradle
        - ..:/atlas
        working_dir: /atlas
        command: echo
