version: "2"
services:
  timelock1:
    hostname: "timelock1"
    build: ..
    environment:
      - HOSTNAME=timelock1
    ports:
     - "3828"
  timelock2:
    hostname: "timelock2"
    build: ..
    environment:
      - HOSTNAME=timelock2
    ports:
     - "3828"
  timelock3:
    hostname: "timelock3"
    build: ..
    environment:
      - HOSTNAME=timelock3
    ports:
     - "3828"
